### ISSUE TITLE
Switch jekyll highlighter

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/devs#11]
Currently, every page build generates this warning from github.

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#fixing-highlighting-errors.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by debloper** [comment]
It seems the only affected instance is: https://github.com/MozillaIndia/devs/blob/master/_config.yml#L4 (and [has just been fixed](https://github.com/MozillaIndia/devs/commit/3b8b378fce4288d9776bfca2916e7a5f0442fd74)). it's unlikely that other pages build will give the same warning.

In case it does, this query will [help find out](https://developer.github.com/v4/explorer/) the repos with pages.

```
{
  organization(login: "MozillaIndia") {
    repositories(last: 25) {
      totalCount
      edges {
        node {
          name
          refs(last: 5, refPrefix: "refs/heads/") {
            nodes {
              name
            }
          }
        }
      }
    }
  }
}

```

It isn't comprehensive, and there isn't a better way to pull repos with GitHub pages from v4 API except for looking at the branch name == `gh-pages` (or docs directory in `master` in some repos, which is bad practice exactly because of this reason). Alternative is to do nested query for each [repo's pages](https://developer.github.com/v3/repos/pages/#get-information-about-a-pages-site) with v3 API.

The solution would be to update the highlighter value in the affected repositories.
